apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  type: NodePort
  selector:
    app: webapp
    release: "0-5"

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010

